### PR TITLE
LIcence is always valid

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Not "until" something:

https://github.com/irgolic/AutoPR/commit/9694ba96863cc48471c71517737ee830784e6688

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
I'm not sure this is the best text, it needs not refer to the year at all?

**Comment by irgolic** [comment]
Hey, sorry for the late response. To be crystal clear, the license is always valid. What you're reading is GPT's interpretation of the MIT license. The part you're editing is autogenerated, and the change would be reverted in its next run.

Thanks for pointing it out, interesting to see gpt-3.5-turbo get something like this wrong!

**Comment by PallHaraldsson** [comment]
Interesting, what is the prompt? I assume the [LICENSE.md](https://github.com/irgolic/AutoPR/blob/b2b4a5bd4e292eda4c0821413a3477a310eca6b8/LICENSE.md) file, in full, not just "MIT license" but but something more, prefix "explain the following file" that you do for any file?

**Comment by irgolic** [comment]
If you'd like to see the exact prompts, try running it with `verbose: true`. It'll then show you all the steps of the process in the PR.

So your trigger file should look something like this:

```yaml
triggers:
  - label_substring: summarize
    on_issue: false
    on_pull_request: true
    run: summarize_pr
    verbose: true
```

**Pull request closed without merging**
